# Generated by Django 2.2.14 on 2020-07-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20200720_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideshow',
            old_name='total_score',
            new_name='total_score1',
        ),
    ]
