# Generated by Django 2.2.14 on 2020-07-20 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_auto_20200720_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='image',
        ),
        migrations.CreateModel(
            name='AttemptedQuestion1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Was this attempt correct?')),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Marks Obtained')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('hint', models.TextField(default='There is no hint for this Question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Question')),
                ('quiz_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='Quiz.slideshow')),
                ('selected_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.Choice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
