# Generated by Django 2.2.14 on 2020-07-20 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_auto_20200720_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedquestion1',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Question1'),
        ),
    ]
