# Generated by Django 2.2.14 on 2020-07-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_auto_20200721_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_published',
        ),
    ]
